image: atlassian/default-image:4

definitions:
  steps:
    - step: &docker-build
        name: Docker Build
        services:
          - docker
        caches:
          - docker
        script:
          - docker info
          - BASE_NAME="${PRIVATE_DOCKER_REGISTRY_URL}/ssz/${BITBUCKET_REPO_SLUG}"
          - BUILD_TAG="build${BITBUCKET_BUILD_NUMBER}_${BITBUCKET_COMMIT:0:7}"
          - docker build --pull -t "${BASE_NAME}:${BUILD_TAG}"
            --build-arg PORT=3001
            --build-arg BASE_URI=http://localhost
            .
          - docker images "${BASE_NAME}:${BUILD_TAG}"
    - step: &docker-build-push
        name: Docker Build & Push
        services:
          - docker
        caches:
          - docker
        script:
          - docker info
          - |
            if [[ "$BITBUCKET_TAG" =~ ^v[0-9.]+$ ]]; then
              # If there's a TAG, set the package-version correctly
              (cd app && npm version "${BITBUCKET_TAG#v}")
            fi
          - docker login -u ${PRIVATE_DOCKER_REGISTRY_USER} --password-stdin ${PRIVATE_DOCKER_REGISTRY_URL} <<<"${PRIVATE_DOCKER_REGISTRY_PASS}"
          - BASE_NAME="${PRIVATE_DOCKER_REGISTRY_URL}/ssz/${BITBUCKET_REPO_SLUG}"
          - BUILD_TAG="build${BITBUCKET_BUILD_NUMBER}_${BITBUCKET_COMMIT:0:7}"
          - BASE_VERSION="$(jq -r '.version' package.json)"
          - docker build --pull -t "${BASE_NAME}:${BUILD_TAG}"
            .
          - docker push "${BASE_NAME}:${BUILD_TAG}"
          - |
            EXTRA_TAGS=()
            if [[ "$BITBUCKET_TAG" =~ ^v[0-9.]+$ ]]; then
              EXTRA_TAGS+=( "${BITBUCKET_TAG#v}" )
            elif [ "$BITBUCKET_BRANCH" == "main" ]; then
              EXTRA_TAGS+=( "$BASE_VERSION" "latest" )
            fi
            for tag in "${EXTRA_TAGS[@]}"; do
              docker tag "${BASE_NAME}:${BUILD_TAG}" "${BASE_NAME}:${tag}"
              docker push "${BASE_NAME}:${tag}"
              echo "Pushed ${BASE_NAME}:${tag}"
            done
          - docker images "${BASE_NAME}:${BUILD_TAG}"

pipelines:
  default:
    - step: *docker-build
  pull-requests:
    '**':
      - step: *docker-build-push
  branches:
    main:
      - step: *docker-build-push
  tags:
    v*:
      - step: *docker-build-push
  custom:
    'Build & Push Docker Image':
      - step: *docker-build-push