FROM node:22-alpine AS build

ARG BASE_URI
ARG BASE_PATH=/api/v1
ARG PUBLIC_URI

ARG DATA_SOURCE_BASE_URL
ARG SPARQL_ENDPOINT
ARG DATA_DIR

ENV BASE_URI=${BASE_URI}
ENV BASE_PATH=${BASE_PATH}
ENV PUBLIC_URI=${PUBLIC_URI}

ENV DATA_SOURCE_BASE_URL=${DATA_SOURCE_BASE_URL}
ENV SPARQL_ENDPOINT=${SPARQL_ENDPOINT}
ENV DATA_DIR=${DATA_DIR}

WORKDIR /usr/src/app

COPY . .

RUN npm install \
    && npm run build:tsc

FROM node:22-alpine

ARG PORT=3001
ARG DATA_SOURCE_BASE_URL
ARG SPARQL_ENDPOINT
ARG DATA_DIR

ENV PORT=${PORT}
ENV DATA_SOURCE_BASE_URL=${DATA_SOURCE_BASE_URL}
ENV SPARQL_ENDPOINT=${SPARQL_ENDPOINT}
ENV DATA_DIR=${DATA_DIR}


WORKDIR /usr/src/app

COPY --from=build /usr/src/app .

RUN npm install --only=production

EXPOSE ${PORT}

# Start the application
CMD ["npm", "start"]