version: '3.8'

services:
  melody-1.1:
    container_name: melody-1.1-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - BASE_URI=http://localhost
      - BASE_PATH=/api/v1