version: '3.8'

services:
  melody-1.2:
    container_name: melody-1.2-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - BASE_URI=http://localhost
      - BASE_PATH=/api/v1
      - PUBLIC_URI=https://melody-1-2-server.ssz.redlink.io
      - SPARQL_ENDPOINT=https://ld.test.stzh.ch/query
      - DATA_SOURCE_BASE_URL=https://ld.integ.stzh.ch/statistics/view/